blueprints.py
import base64
import json
import os
import sys
from datetime import date, datetime
from io import BytesIO

import jwt
from flask import (
    Blueprint,
    Response,
    current_app,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    session,
)
from flask_httpauth import HTTPBasicAuth
from PIL import Image
from werkzeug.datastructures import FileStorage
from werkzeug.security import check_password_hash, generate_password_hash

from database import (
    delete_image_by_uuid,
    get_all_resources,
    get_all_unlocked_resources_and_the_next_locked_one,
    get_resource_file,
    get_resource_metadata,
    get_resource_metadata_json,
    store_file,
    update_resource_metadata,
    upload_resource_metadata,
)
from entities import ResourceFile, ResourceMetadata
from utils import IMAGE_FORMAT_MAPPING, MIMETYPE_MAPPING, thumbnail_image

blueprint_backend = Blueprint("backend", __name__)


auth = HTTPBasicAuth()

JWT_SECRET = os.environ.get("JWT_SECRET")


class AuthenticationError(Exception):
    pass


def verify_jwt(request):
    if "token" in session:
        jwt_decoded = jwt.decode(session["token"], JWT_SECRET, algorithms=["HS256"])
        if not jwt_decoded["user"] in json.loads(os.environ.get("USERS")).keys():
            raise AuthenticationError("Your session token seems to be broken!")
    else:
        auth_header = request.headers.get("Authorization")
        if not auth_header:
            raise AuthenticationError("You cannot access this without an authorization header!")
        jwt_token = auth_header.split("Bearer ")[1]
        jwt_decoded = jwt.decode(jwt_token, JWT_SECRET, algorithms=["HS256"])
        # print(jwt_decoded, file=sys.stderr)
        api_key = os.environ.get("API_KEY")
        if not jwt_decoded["api_key"] == api_key:
            raise AuthenticationError("Your JWT Token does not have a valid API Key!")
    return True


@auth.verify_password
def verify_password(username: str, password: str) -> bool:
    users = json.loads(os.environ.get("USERS"))

    login_successful = username in users and check_password_hash(
        users.get(username), password
    )
    if login_successful:
        session["token"] = jwt.encode({"user": username}, JWT_SECRET, algorithm="HS256")
    return login_successful


@blueprint_backend.route("/auth_api_key", methods=["POST"])
def auth_api_key():
    api_key = request.json.get("api_key")
    if not api_key:
        raise AuthenticationError("You must provide a valid API Key to validate yourself.")
    
    if api_key == os.environ.get("API_KEY"):
        return jwt.encode({"api_key": api_key}, JWT_SECRET, algorithm="HS256")

@blueprint_backend.route("/get_all_available_resources", methods=["GET"])
def blueprint_get_all_available_resources():
    if not verify_jwt(request):
        raise AuthenticationError("Something went wrong with the authentication!")

    return get_all_unlocked_resources_and_the_next_locked_one()


@blueprint_backend.route("/meta", methods=["GET"])
def blueprint_get_resource_meta(uuid=None):
    if not verify_jwt(request):
        raise AuthenticationError("Something went wrong with the authentication!")

    if not uuid:
        uuid = request.args["uuid"]
    if not uuid:
        raise ValueError("Please provide the uuid.")
    meta = get_resource_metadata_json(uuid)
    if not meta:
        raise FileNotFoundError(f"The meta with uuid {uuid} does not exist.")

    return meta


@blueprint_backend.route("/resource", methods=["GET"])
def blueprint_get_resource_file(uuid=None):
    if not verify_jwt(request):
        raise AuthenticationError("Something went wrong with the authentication!")

    if not uuid:
        uuid = request.args["uuid"]
    if not uuid:
        raise ValueError("Please provide the uuid.")
    image_data = get_resource_file(uuid)
    if not image_data:
        raise FileNotFoundError(f"The file with uuid {uuid} does not exist.")
    image_metadata = get_resource_metadata(uuid)
    image_stream = BytesIO(image_data)
    file_name = image_metadata["file_name"]
    file_ending = file_name.split(".")[-1]

    mimetype = MIMETYPE_MAPPING[file_ending.lower()]
    print(f"{file_name}: {mimetype}", file=sys.stderr)
    return send_file(image_stream, mimetype=mimetype, download_name=file_name)


@blueprint_backend.route("/uploader", methods=["GET", "POST"])
@auth.login_required
def uploader():
    if request.method == "POST":
        creation_date = datetime.strptime(
            request.form.get("creation_date"), "%d.%m.%Y"
        ).date()

        inputs = {
            "file": request.files["file"],
            "file_name": request.files["file"].filename,
            "creation_date": creation_date,
            "title": request.form.get("title"),
            "caption": request.form.get("caption"),
            "uploaded_by": request.form.get("uploaded_by"),
        }

        if inputs["file_name"].split(".")[1].lower() not in MIMETYPE_MAPPING.keys():
            return render_template(
                "uploader.html",
                result="Bitte verwende nur Bilder im Format PNG oder JPEG! ⚠️",
            )

        required = [
            "file",
            "creation_date",
            "title",
            "uploaded_by",
        ]


        for key in required:
            if not inputs[key]:
                raise ValueError(f"The form parameter '{key}' must be provided.")

        resource_metadata = ResourceMetadata(
            inputs["file_name"],
            inputs["creation_date"],
            inputs["title"],
            inputs["caption"],
            inputs["uploaded_by"],
        )

        image_file = inputs["file"]

        try:
            img = Image.open(image_file)
            downscaled_img = thumbnail_image(img)
            image_io = BytesIO()

            file_name = request.files["file"].filename
            file_ending = file_name.split(".")[1]
            image_format = IMAGE_FORMAT_MAPPING[file_ending]
            mimetype = MIMETYPE_MAPPING[file_ending.lower()]

            print(
                f"Saving img {file_name}: {image_format}, {mimetype}", file=sys.stderr
            )
            downscaled_img.save(image_io, format=image_format)
            image_io.seek(0)  # Reset the BytesIO position to the beginning
            image_file = FileStorage(
                stream=image_io,
                filename=file_name,
                content_type=mimetype,
            )
        except KeyError as key_error:
            print(key_error, file=sys.stderr)
        except Exception as e:
            print(e, file=sys.stderr)

        file_resource = ResourceFile(uuid=resource_metadata.uuid, file=image_file)

        metadata_result = upload_resource_metadata(resource_metadata)
        metadata_file_result = store_file(file_resource)
        if metadata_result["uuid"] and metadata_file_result["uuid"]:
            return render_template(
                "uploader.html",
                result="Der Upload war erfolgreich! 🥳",
                name=auth.current_user(),
            )
        else:
            return render_template(
                "uploader.html",
                result="Da ist etwas schief gelaufen! 🤯",
                name=auth.current_user(),
            )

    # If it's a GET request, render the uploader html page
    return render_template(
        "uploader.html",
        result="Uploade ein Bild für Flo! 🖼️",
        name=auth.current_user(),
    )


@blueprint_backend.route("/", methods=["GET"])
@auth.login_required
def show_images():
    resources = get_all_resources()
    return render_template("show_images.html", images=resources)


@blueprint_backend.route("/edit_image", methods=["GET", "POST"])
@auth.login_required
def edit_image(uuid=None):
    if request.method == "POST":
        uuid = request.form.get("uuid")
        title = request.form.get("title")
        caption = request.form.get("caption")
        uploaded_by = request.form.get("uploaded_by")
        creation_date = request.form.get("creation_date")
        try:
            creation_date = datetime.fromisoformat(creation_date).date()
        except Exception as e:
            image_metadata = get_resource_metadata(uuid)
            return render_template("edit_image.html", image=image_metadata, error=e)

        image_metadata = update_resource_metadata(
            uuid, title, caption, uploaded_by, creation_date
        )
        return redirect("/")
    else:
        if not uuid:
            uuid = request.args["uuid"]
        if not uuid:
            raise ValueError("Please provide the uuid.")

        image_metadata = get_resource_metadata(uuid)
        return render_template("edit_image.html", image=image_metadata, error="")


@blueprint_backend.route("/delete_image", methods=["DELETE"])
@auth.login_required
def delete_image(uuid=None):
    if not uuid:
        uuid = request.args["uuid"]
    if not uuid:
        raise ValueError("Please provide the uuid.")

    delete_image_by_uuid(uuid)

    response_data = {"message": "Image deleted successfully"}

    return jsonify(response_data), 302, {"Location": "/"}

templates/edit_image.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bild bearbeiten</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
</head>

<body>
    <nav class="demo">
        <a class="brand">
            <img class="logo" src="https://cdn-icons-png.flaticon.com/512/2590/2590735.png" />
            <span>Flos Farewell</span>
        </a>

        <!-- responsive-->
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button">Menu</label>

        <div class="menu">
            <a href="/uploader" class="button icon-picture">Bilder uploaden</a>
            <a href="/" class="button icon-puzzle">Bilder ansehen und bearbeiten</a>
        </div>
    </nav>

    <div style="padding: 30px;">
        <h1>Bild bearbeiten</h1>
        <p>{{ error }}</p>
    </div>

    <article class="card" style="margin: 2%; padding: 2%;">

        <form method="post" enctype="multipart/form-data">
            <input type="hidden" name="uuid" value="{{ image['uuid'] }}" required>
            <div>
                <label for="title">Title:</label>
                <input type="text" id="title" name="title" value="{{ image['title'] }}" required>
            </div>
            <div>
                <label for="caption">Caption:</label>
                <textarea id="caption" name="caption">{{ image["caption"] }}</textarea>
            </div>
            <div>
                <label for="uploaded_by">Uploaded By:</label>
                <input type="text" id="uploaded_by" name="uploaded_by" value="{{ image['uploaded_by'] }}" required>
            </div>
            <div>
                <label for="creation_date">Creation Date:</label>
                <input type="text" id="creation_date" name="creation_date" value="{{ image['creation_date'] }}"
                    required>
            </div>
            <div>
                <img src="{{ url_for('backend.blueprint_get_resource_file', uuid=image['uuid']) }}" alt="{{ image["
                    title"]}}" style="max-width: 100%; max-height: 100%;">
            </div>
            <footer>
                <div>
                    <input type="submit" value="Update">
                </div>
            </footer>
        </form>
        <button class="error" onclick="deleteImage('{{ image.uuid }}')">Delete</button>
    </article>
</body>

<script>
    function deleteImage(uuid) {
        console.log("Deleting image...")
        if (confirm("Bist du dir sicher, dass du das Bild löschen willst?")) {
            fetch_url = "{{ url_for('backend.delete_image')}}" + "?uuid=" + uuid;
            console.log(fetch_url);
            fetch(fetch_url, {
                method: 'DELETE',
            }).finally(function () {
                window.location.href = "{{ url_for('backend.show_images') }}"
            })
        }
    }
</script>

</html>

templates/error.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bild bearbeiten</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
</head>

<body>
    <nav class="demo">
        <a class="brand">
            <img class="logo" src="https://cdn-icons-png.flaticon.com/512/2590/2590735.png" />
            <span>Flos Farewell</span>
        </a>

        <!-- responsive-->
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button">Menu</label>

        <div class="menu">
            <a href="/uploader" class="button icon-picture">Bilder uploaden</a>
            <a href="/" class="button icon-puzzle">Bilder ansehen und bearbeiten</a>
        </div>
    </nav>


    <article class="card" style="margin: 2%; padding: 2%;">
        <h1>Tut mir leid, da gab es einen Fehler 😥</h1>
        <h2>{{status_code}}: {{error}}</h2>
        <h2>{{message}}</h2>
        <h4>{{trace}}</h4>
    </article>
</body>

</html>

templates/show_images.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alle Bilder</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
</head>

<body>
    <nav class="demo">
        <a class="brand">
            <img class="logo" src="https://cdn-icons-png.flaticon.com/512/2590/2590735.png" />
            <span>Flos Farewell</span>
        </a>

        <!-- responsive-->
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button">Menu</label>

        <div class="menu">
            <a href="/uploader" class="button icon-picture">Bilder uploaden</a>
            <a href="/" class="button icon-puzzle">Bilder ansehen und bearbeiten</a>
        </div>
    </nav>

    <div style="padding: 30px;">
        <h1>Alle Bilder</h1>
    </div>

    {% for image in images %}
    <article class="card" style="margin: 2%; padding: 2%;">
        <header>
            <h1>{{ image['title'] }}</h1>
        </header>
        <div>
            <img src="{{ url_for('backend.blueprint_get_resource_file', uuid=image['uuid']) }}" alt="{{ image["
                title"]}}" style="max-height:100%; max-width:100%;">
        </div>
        <footer>
            <p><b>Bildunterschrift:</b> {{ image['caption'] }}</p>
            <p><b>Aufnahmedatum:</b> {{ image['creation_date'] }}</p>
            <p><b>Hochgeladen von:</b> {{ image['uploaded_by'] }}</p>
            <button onclick="editImage('{{ image.uuid }}')">Bild bearbeiten</button>
        </footer>
    </article>
    {% endfor %}
</body>

<script>
    function editImage(uuid) {
        // Redirect to the /edit_image?uuid=uuid
        window.location.href = '/edit_image?uuid=' + uuid;
    }
</script>

</html>

templates/uploader.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uploader</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/exif-js/2.3.0/exif.js"></script>
</head>

<body>
    <nav class="demo">
        <a class="brand">
            <img class="logo" src="https://cdn-icons-png.flaticon.com/512/2590/2590735.png" />
            <span>Flos Farewell</span>
        </a>

        <!-- responsive-->
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button">Menu</label>

        <div class="menu">
            <a href="/uploader" class="button icon-picture">Bilder uploaden</a>
            <a href="/" class="button icon-puzzle">Bilder ansehen und bearbeiten</a>
        </div>
    </nav>

    <div style="padding: 30px;">
        <h1>Bilder Upload</h1>
        <h2>Hi, {{name}}!</h2>
        <h3>{{result}}</h3>
    </div>

    <article class="card" style="margin: 2%; padding: 2%;">
        <form method="post" enctype="multipart/form-data">
            <label for="file"><h1>Bild auswählen:</h1></label>
            <div style="max-height: 20%; width: auto; "> <!-- this div just for demo display -->
                <label class="dropimage">
                    <input title="Bild hier auswählen." type="file" name="file">
                </label>
            </div>
            <br>

            <label for="title"><b>Titel:</b></label>
            <input type="text" name="title" required>
            <br>

            <label for="caption">Bildunterschrift (optional):</label>
            <input type="text" name="caption">
            <br>

            <label for="uploaded_by">Dein Name:</label>
            <input type="text" name="uploaded_by" value="{{name}}" required>
            <br>

            <label for="creation_date">Aufnahmedatum (wird in der Regel automatisch gefunden):</label>
            <input type="text" name="creation_date" required>
            <br>

            <footer>
                <button type="submit">Abschicken</button>
            </footer>
        </form>
    </article>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            [].forEach.call(document.querySelectorAll('.dropimage'), function (img) {
                img.onchange = function (e) {
                    var inputfile = this, reader = new FileReader();
                    reader.onloadend = function () {
                        inputfile.style['background-image'] = 'url(' + reader.result + ')';
                    }
                    reader.readAsDataURL(e.target.files[0]);
                }
            });
        });

        document.addEventListener('DOMContentLoaded', function () {
            // Get the file input element
            var fileInput = document.querySelector('input[name="file"]');

            // Get the creation date input element
            var creationDateInput = document.querySelector('input[name="creation_date"]');

            // Add an event listener for the file input change event
            fileInput.addEventListener('change', function (event) {
                creationDateInput.value = "";
                // Get the selected file
                var selectedFile = event.target.files[0];

                if (!selectedFile || !selectedFile.type.startsWith('image/')) throw new Error("The file has to be an image file!");

                var creationDate = getCDateFromEXIF(selectedFile);
                if (!creationDate) {
                    creationDate = extractCDateFromFilename(selectedFile.name);
                } else {
                    console.log("Found creation date in EXIF data.")
                }
                if (!creationDate) {
                    creationDate = new Date(selectedFile.lastModified);
                    console.log("Found creation date in mtime.");
                } else {
                    console.log("Found creation date in filename.")
                }

                creationDateInput.value = dateToGermanFormat(creationDate);

            });

            function getCDateFromEXIF(selectedFile) {
                // Use exif.js to read EXIF data
                EXIF.getData(selectedFile, function () {
                    var exifDate = EXIF.getTag(this, "DateTimeOriginal");
                    if (exifDate) {
                        const year = exifDate.substr(0, 4);
                        const month = exifDate.substr(5, 2);
                        const day = exifDate.substr(8, 2);

                        return new Date(year + "-" + month + "-" + day);
                    }
                });
                // Return null if no EXIF date is found
                return null;
            }

            function extractCDateFromFilename(filename) {
                // Define the regular expression pattern
                const regex = /IMG-(\d{8})/;

                // Use the exec method to match the pattern against the filename
                const match = regex.exec(filename);

                // Check if there is a match
                if (match && match[1]) {
                    // Extracted date in the format YYYYMMDD
                    const dateStr = match[1];
                    // Parse the date string into a JavaScript Date object
                    const year = dateStr.substr(0, 4);
                    const month = dateStr.substr(4, 2);
                    const day = dateStr.substr(6, 2);

                    console.log(year + "-" + month + "-" + day);

                    return new Date(year + "-" + month + "-" + day);
                } else {
                    // Return null if no match is found
                    return null;
                }
            }


            function dateToGermanFormat(date) {
                var dateStr = date.toISOString().split("T")[0];
                const year = dateStr.substr(0, 4);
                const month = dateStr.substr(5, 2);
                const day = dateStr.substr(8, 2);
                return day + "." + month + "." + year
            }

        });
    </script>

</body>

</html>